version: 2
jobs:
  build:
    docker:
      - image: ruby:2.4.4
    steps:
      - checkout
      - run:
        - name: Installing dependencies
        - command: bundle install
      - run:
        - name: Running echo
        - command: echo "Hello"
  test:
    override:
      - bundle exec rspec --format progress --format RspecJunitFormatter -o $CIRCLE_TEST_REPORTS/rspec.xml
workflows:
  version: 2
  build_only:
    jobs:
      - build
