version: 2
jobs:
  build:
    machine:
      ruby:
        version: 2.4.4
    steps:
      - checkout
      - run: bundle install
      - run: echo "hello"
  # test:
  #   docker:
  #     - image: circleci/<language>:<version TAG>
  #   steps:
  #     - checkout
  #     - run: <command>
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
