version: 2
jobs:
  build:
    machine:
      ruby:
        version: 2.4.4
    steps:
      - checkout
      - run: bundle install
      - run: echo "hello world"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build

notify:
  webhooks:
    # A list of hashes representing hooks. Only the url field is supported.
    - url: https://hooks.slack.com/services/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
